require 'rake'
require 'rspec/core/rake_task'
require 'yaml'
require 'highline/import'
require "pry"

properties = YAML.load_file('properties.yaml')
desc "Run serverspec to all hosts"
task :serverspec => 'serverspec:all'

namespace :serverspec do
  task :all => properties.keys.map {|key| 'serverspec:' + key }
  properties.keys.each do |key|
    desc "Run serverspec to #{key}"
    RSpec::Core::RakeTask.new(key.to_sym) do |t|
      ENV['TARGET_HOST'] = properties[key][:hostname]
      ENV['SSH_USER'] = properties[key][:username]
      ENV['SSH_KEY'] = properties[key][:key]
      t.pattern = 'spec/{' + properties[key][:roles].join(',') + '}/*_spec.rb'
    end
  end
end
